apiVersion: apps/v1
kind: Deployment
metadata:
  name: openwebui
  namespace: openwebui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openwebui
  template:
    metadata:
      labels:
        app: openwebui
    spec:
      volumes:
      - name: openwebui-data
        persistentVolumeClaim:
          claimName: openwebui-data-pvc
      containers:
      - name: openwebui
        image: ghcr.io/open-webui/open-webui:main
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: openwebui-config
        volumeMounts:
        - name: openwebui-data
          mountPath: /app/backend/data
        resources:
          limits:
            memory: "2Gi"
          requests:
            memory: "1Gi"
