apiVersion: v1
kind: PersistentVolume
metadata:
  name: triton-models-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /models/triton/model_repo
    type: DirectoryOrCreate
